version: '3'
services:
    api:
      image: container_fastapi
      depends_on:
      - postgres
      ports:
        - 8000:8000  
      env_file:
        - ./.env
      # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
      
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
